# Application Configuration
spring:
  application:
    name: Student  # Application name

  # Database Configuration
  datasource:
    url: jdbc:mysql://database-1.cl02oeaiyql0.ap-south-1.rds.amazonaws.com:3306/student?useSSL=false&serverTimezone=UTC  # AWS RDS database URL
    username: admin  # AWS RDS database username
    password: 9eTFUQ831poKvQu25FRW  # AWS RDS database password (Consider using environment variables instead of hardcoding)
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver

  # JPA & Hibernate Settings
  jpa:
    hibernate:
      ddl-auto: update  # Auto-update the database schema
    show-sql: true  # Enable SQL query logging
    database-platform: org.hibernate.dialect.MySQL8Dialect  # Use MySQL 8 dialect

# Server Configuration
server:
  port: 9090  # Application will run on port 9090

# -----------------------------------------------
# Local Database Configuration (Uncomment to use)
# -----------------------------------------------
# spring:
#   datasource:
#     url: jdbc:mysql://localhost:3306/student?useSSL=false&serverTimezone=UTC  # Local MySQL database URL
#     username: root  # Local database username
#     password: root  # Local database password
#     driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL JDBC driver
